// angular-material/src/app/charts/more-charts/basic-boxplot-chart/basic-boxplot-chart.component.ts
import { Component, ViewChild } from '@angular/core';
import { MatCardModule } from '@angular/material/card';
import { RouterLink } from '@angular/router';

import {
    ApexAxisChartSeries,
    ChartComponent,
    ApexChart,
    ApexPlotOptions,
    ApexTitleSubtitle,
    ApexLegend,
    ApexXAxis,
    ApexGrid,
    ApexYAxis,
    ApexTooltip,
    NgApexchartsModule
} from "ng-apexcharts";

export type ChartOptions = {
    series: ApexAxisChartSeries;
    chart: ApexChart;
    title: ApexTitleSubtitle;
    xaxis: ApexXAxis,
    yaxis: ApexYAxis,
    grid: ApexGrid,
    legend: ApexLegend,
    tooltip: ApexTooltip,
    plotOptions: ApexPlotOptions;
    colors: string[]
};

@Component({
    selector: 'app-basic-boxplot-chart',
    standalone: true,
    imports: [RouterLink, MatCardModule, NgApexchartsModule],
    templateUrl: './basic-boxplot-chart.component.html',
    styleUrl: './basic-boxplot-chart.component.scss'
})
export class BasicBoxplotChartComponent {

    @ViewChild("chart") chart: ChartComponent;
    public chartOptions: Partial<ChartOptions>;

    constructor() {
        this.chartOptions = {
            series: [
                {
                    name: 'Box',
                    type: 'boxPlot',
                    data: [
                        {
                            x: new Date('2017-01-01').getTime(),
                            y: [54, 66, 69, 75, 88]
                        },
                        {
                            x: new Date('2018-01-01').getTime(),
                            y: [43, 65, 69, 76, 81]
                        },
                        {
                            x: new Date('2019-01-01').getTime(),
                            y: [31, 39, 45, 51, 59]
                        },
                        {
                            x: new Date('2020-01-01').getTime(),
                            y: [39, 46, 55, 65, 71]
                        },
                        {
                            x: new Date('2021-01-01').getTime(),
                            y: [29, 31, 35, 39, 44]
                        }
                    ]
                },
                {
                    name: 'Outliers',
                    type: 'scatter',
                    data: [
                        {
                            x: new Date('2017-01-01').getTime(),
                            y: 32
                        },
                        {
                            x: new Date('2018-01-01').getTime(),
                            y: 25
                        },
                        {
                            x: new Date('2019-01-01').getTime(),
                            y: 64
                        },
                        {
                            x: new Date('2020-01-01').getTime(),
                            y: 27
                        },
                        {
                            x: new Date('2020-01-01').getTime(),
                            y: 78
                        },
                        {
                            x: new Date('2021-01-01').getTime(),
                            y: 15
                        }
                    ]
                }
            ],
            chart: {
                height: 350,
                type: "boxPlot",
                toolbar: {
                    show: true
                }
            },
            colors: [
                '#605DFF', '#3584FC'
            ],
            title: {
                text: 'BoxPlot - Scatter Chart',
                align: 'left',
                offsetX: -9,
                style: {
                    fontWeight: '500',
                    fontSize: '14px',
                    color: '#64748B'
                }
            },
            xaxis: {
                type: 'datetime',
                axisTicks: {
                    show: false,
                    color: '#ECEEF2'
                },
                axisBorder: {
                    show: false,
                    color: '#ECEEF2'
                },
                labels: {
                    show: true,
                    style: {
                        colors: "#8695AA",
                        fontSize: "12px"
                    }
                }
            },
            tooltip: {
                shared: false,
                intersect: true
            },
            yaxis: {
                labels: {
                    show: true,
                    style: {
                        colors: "#64748B",
                        fontSize: "12px"
                    }
                },
                axisBorder: {
                    show: false,
                    color: '#ECEEF2'
                },
                axisTicks: {
                    show: false,
                    color: '#ECEEF2'
                }
            },
            grid: {
                show: true,
                borderColor: "#ECEEF2"
            },
            legend: {
                show: true,
                position: 'top',
                fontSize: '12px',
                horizontalAlign: 'center',
                itemMargin: {
                    horizontal: 8,
                    vertical: 0
                },
                labels: {
                    colors: '#64748B'
                },
                markers: {
                    width: 9,
                    height: 9,
                    offsetX: -2,
                    offsetY: -.5
                }
            }
        };
    }

}
<mat-card class="mb-25 border-radius d-block bg-white border-0 shadow-none">
    <mat-card-header>
        <mat-card-title>
            <h5 class="mb-0">
                Basic Boxplot Chart
            </h5>
        </mat-card-title>
    </mat-card-header>
    <mat-card-content>
        <div class="chart">
            <apx-chart
                [series]="chartOptions.series!"
                [chart]="chartOptions.chart!"
                [xaxis]="chartOptions.xaxis!"
                [title]="chartOptions.title!"
                [colors]="chartOptions.colors!"
                [legend]="chartOptions.legend!"
                [tooltip]="chartOptions.tooltip!"
                [grid]="chartOptions.grid!"
            ></apx-chart>
        </div>
    </mat-card-content>
</mat-card>

// nextjs-material-ui/src/components/Charts/MoreCharts/BasicBoxplotChart.tsx
"use client";

import React, { useEffect, useState } from "react";
import { ApexOptions } from "apexcharts";
import dynamic from "next/dynamic";
import {
  Card,
  Box,
  Typography,
} from "@mui/material";

// Dynamically import react-apexcharts with Next.js dynamic import
const Chart = dynamic(() => import("react-apexcharts"), { ssr: false });

const BasicBoxplotChart: React.FC = () => {

  // Chart
  const [isChartLoaded, setChartLoaded] = useState(false);

  useEffect(() => {
    setChartLoaded(true);
  }, []);

  const series = [
    {
      name: 'Box',
      type: 'boxPlot',
      data: [
          {
              x: new Date('2017-01-01').getTime(),
              y: [54, 66, 69, 75, 88]
          },
          {
              x: new Date('2018-01-01').getTime(),
              y: [43, 65, 69, 76, 81]
          },
          {
              x: new Date('2019-01-01').getTime(),
              y: [31, 39, 45, 51, 59]
          },
          {
              x: new Date('2020-01-01').getTime(),
              y: [39, 46, 55, 65, 71]
          },
          {
              x: new Date('2021-01-01').getTime(),
              y: [29, 31, 35, 39, 44]
          }
      ]
  },
  {
      name: 'Outliers',
      type: 'scatter',
      data: [
          {
              x: new Date('2017-01-01').getTime(),
              y: 32
          },
          {
              x: new Date('2018-01-01').getTime(),
              y: 25
          },
          {
              x: new Date('2019-01-01').getTime(),
              y: 64
          },
          {
              x: new Date('2020-01-01').getTime(),
              y: 27
          },
          {
              x: new Date('2020-01-01').getTime(),
              y: 78
          },
          {
              x: new Date('2021-01-01').getTime(),
              y: 15
          }
      ]
  }
  ];

  const options: ApexOptions = {
    chart: {
 
      toolbar: {
          show: true
      }
  },
  colors: [
      '#605DFF', '#3584FC'
  ],
  title: {
      text: 'BoxPlot - Scatter Chart',
      align: 'left',
      offsetX: -9,
      style: {
          fontWeight: '500',
          fontSize: '14px',
          color: '#64748B'
      }
  },
  xaxis: {
      type: 'datetime',
      axisTicks: {
          show: false,
          color: '#ECEEF2'
      },
      axisBorder: {
          show: false,
          color: '#ECEEF2'
      },
      labels: {
          show: true,
          style: {
              colors: "#8695AA",
              fontSize: "12px"
          }
      }
  },
  tooltip: {
      shared: false,
      intersect: true
  },
  yaxis: {
      labels: {
          show: true,
          style: {
              colors: "#64748B",
              fontSize: "12px"
          }
      },
      axisBorder: {
          show: false,
          color: '#ECEEF2'
      },
      axisTicks: {
          show: false,
          color: '#ECEEF2'
      }
  },
  grid: {
      show: true,
      borderColor: "#ECEEF2"
  },
  legend: {
      show: true,
      position: 'top',
      fontSize: '12px',
      horizontalAlign: 'center',
      itemMargin: {
          horizontal: 8,
          vertical: 0
      },
      labels: {
          colors: '#64748B'
      },
      markers: {
          offsetX: -2,
          offsetY: -.5
      }
  }
  };

  return (
    <>
      <Card
        sx={{
          boxShadow: "none",
          borderRadius: "7px",
          mb: "25px",
          padding: { xs: "18px", sm: "20px", lg: "25px" },
        }}
        className="rmui-card"
      >
        <Typography
          variant="h3"
          sx={{
            fontSize: { xs: "16px", md: "18px" },
            fontWeight: 700,
            mb: "25px",
          }}
          className="text-black"
        >
          Basic Boxplot Chart
        </Typography>

        <Box
          sx={{
            marginBottom: "-20px", 
          }}
        >
          {isChartLoaded && (
            <Chart
              options={options}
              series={series}
              type="boxPlot"
              height={350}
              width={"100%"}
            />
          )}
        </Box>
      </Card>
    </>
  );
};

export default BasicBoxplotChart;
