// angular-material/src/app/charts/more-charts/basic-range-area-chart/basic-range-area-chart.component.ts
import { Component, ViewChild } from '@angular/core';
import { MatCardModule } from '@angular/material/card';
import { RouterLink } from '@angular/router';

import {
    ChartComponent,
    ApexAxisChartSeries,
    ApexChart,
    ApexTitleSubtitle,
    ApexXAxis,
    ApexDataLabels,
    ApexStroke,
    ApexGrid,
    ApexYAxis,
    ApexMarkers,
    NgApexchartsModule
} from "ng-apexcharts";

export type ChartOptions = {
    series: ApexAxisChartSeries;
    chart: ApexChart;
    dataLabels: ApexDataLabels;
    stroke: ApexStroke;
    xaxis: ApexXAxis;
    grid: ApexGrid;
    yaxis: ApexYAxis;
    title: ApexTitleSubtitle;
    colors: any;
    markers: ApexMarkers;
};

@Component({
    selector: 'app-basic-range-area-chart',
    standalone: true,
    imports: [RouterLink, MatCardModule, NgApexchartsModule],
    templateUrl: './basic-range-area-chart.component.html',
    styleUrl: './basic-range-area-chart.component.scss'
})
export class BasicRangeAreaChartComponent {

    @ViewChild("chart") chart: ChartComponent;
    public chartOptions: Partial<ChartOptions>;

    constructor() {
        this.chartOptions = {
            series: [
                {
                    name: "New York Temperature",
                    data: [
                        {
                            x: "Jan",
                            y: [-2, 4]
                        },
                        {
                            x: "Feb",
                            y: [-1, 6]
                        },
                        {
                            x: "Mar",
                            y: [3, 10]
                        },
                        {
                            x: "Apr",
                            y: [8, 16]
                        },
                        {
                            x: "May",
                            y: [13, 22]
                        },
                        {
                            x: "Jun",
                            y: [18, 26]
                        },
                        {
                            x: "Jul",
                            y: [21, 29]
                        },
                        {
                            x: "Aug",
                            y: [21, 28]
                        },
                        {
                            x: "Sep",
                            y: [17, 24]
                        },
                        {
                            x: "Oct",
                            y: [11, 18]
                        },
                        {
                            x: "Nov",
                            y: [6, 12]
                        },
                        {
                            x: "Dec",
                            y: [1, 7]
                        }
                    ]
                }
            ],
            chart: {
                height: 350,
                type: "rangeArea",
                toolbar: {
                    show: true
                }
            },
            stroke: {
                curve: "straight"
            },
            title: {
                text: "New York Temperature (all year round)",
                align: "left",
                offsetX: -9,
                style: {
                    fontWeight: '500',
                    fontSize: '14px',
                    color: '#64748B'
                }
            },
            colors: [
                "#605DFF"
            ],
            markers: {
                hover: {
                    sizeOffset: 5
                }
            },
            dataLabels: {
                enabled: false
            },
            yaxis: {
                labels: {
                    show: true,
                    formatter: (val) => {
                        return val + "°C";
                    },
                    style: {
                        colors: "#64748B",
                        fontSize: "12px"
                    }
                },
                axisBorder: {
                    show: false,
                    color: '#ECEEF2'
                },
                axisTicks: {
                    show: false,
                    color: '#ECEEF2'
                }
            },
            xaxis: {
                axisTicks: {
                    show: false,
                    color: '#ECEEF2'
                },
                axisBorder: {
                    show: false,
                    color: '#ECEEF2'
                },
                labels: {
                    show: true,
                    style: {
                        colors: "#8695AA",
                        fontSize: "12px"
                    }
                }
            },
            grid: {
                show: true,
                borderColor: "#ECEEF2"
            }
        };
    }

}
<mat-card class="mb-25 border-radius d-block bg-white border-0 shadow-none">
    <mat-card-header>
        <mat-card-title>
            <h5 class="mb-0">
                Basic Range Area Chart
            </h5>
        </mat-card-title>
    </mat-card-header>
    <mat-card-content>
        <div class="chart">
            <apx-chart
                [series]="chartOptions.series!"
                [chart]="chartOptions.chart!"
                [dataLabels]="chartOptions.dataLabels!"
                [markers]="chartOptions.markers!"
                [xaxis]="chartOptions.xaxis!"
                [grid]="chartOptions.grid!"
                [yaxis]="chartOptions.yaxis!"
                [stroke]="chartOptions.stroke!"
                [colors]="chartOptions.colors!"
                [title]="chartOptions.title!"
            ></apx-chart>
        </div>
    </mat-card-content>
</mat-card>

// nextjs-material-ui/src/components/Charts/MoreCharts/BasicRangeAreaChart.tsx
"use client";

import React, { useEffect, useState } from "react";
import { ApexOptions } from "apexcharts";
import dynamic from "next/dynamic";
import {
  Card,
  Box,
  Typography,
} from "@mui/material";

// Dynamically import react-apexcharts with Next.js dynamic import
const Chart = dynamic(() => import("react-apexcharts"), { ssr: false });

const BasicRangeAreaChart: React.FC = () => {

  // Chart
  const [isChartLoaded, setChartLoaded] = useState(false);

  useEffect(() => {
    setChartLoaded(true);
  }, []);

  const series = [
    {
      name: "New York Temperature",
      data: [
          {
              x: "Jan",
              y: [-2, 4]
          },
          {
              x: "Feb",
              y: [-1, 6]
          },
          {
              x: "Mar",
              y: [3, 10]
          },
          {
              x: "Apr",
              y: [8, 16]
          },
          {
              x: "May",
              y: [13, 22]
          },
          {
              x: "Jun",
              y: [18, 26]
          },
          {
              x: "Jul",
              y: [21, 29]
          },
          {
              x: "Aug",
              y: [21, 28]
          },
          {
              x: "Sep",
              y: [17, 24]
          },
          {
              x: "Oct",
              y: [11, 18]
          },
          {
              x: "Nov",
              y: [6, 12]
          },
          {
              x: "Dec",
              y: [1, 7]
          }
      ]
  }
  ];

  const options: ApexOptions = {
    chart: {
      toolbar: {
          show: true
      }
  },
  stroke: {
      curve: "straight"
  },
  title: {
      text: "New York Temperature (all year round)",
      align: "left",
      offsetX: -9,
      style: {
          fontWeight: '500',
          fontSize: '14px',
          color: '#64748B'
      }
  },
  colors: [
      "#605DFF"
  ],
  markers: {
      hover: {
          sizeOffset: 5
      }
  },
  dataLabels: {
      enabled: false
  },
  yaxis: {
      labels: {
          show: true,
          formatter: (val) => {
              return val + "°C";
          },
          style: {
              colors: "#64748B",
              fontSize: "12px"
          }
      },
      axisBorder: {
          show: false,
          color: '#ECEEF2'
      },
      axisTicks: {
          show: false,
          color: '#ECEEF2'
      }
  },
  xaxis: {
      axisTicks: {
          show: false,
          color: '#ECEEF2'
      },
      axisBorder: {
          show: false,
          color: '#ECEEF2'
      },
      labels: {
          show: true,
          style: {
              colors: "#8695AA",
              fontSize: "12px"
          }
      }
  },
  grid: {
      show: true,
      borderColor: "#ECEEF2"
  }
  };

  return (
    <>
      <Card
        sx={{
          boxShadow: "none",
          borderRadius: "7px",
          mb: "25px",
          padding: { xs: "18px", sm: "20px", lg: "25px" },
        }}
        className="rmui-card"
      >
        <Typography
          variant="h3"
          sx={{
            fontSize: { xs: "16px", md: "18px" },
            fontWeight: 700,
            mb: "25px",
          }}
          className="text-black"
        >
          Basic Range Area Chart
        </Typography>

        <Box
          sx={{
            marginBottom: "-20px", 
          }}
        >
          {isChartLoaded && (
            <Chart
              options={options}
              series={series}
              type="rangeArea"
              height={350}
              width={"100%"}
            />
          )}
        </Box>
      </Card>
    </>
  );
};

export default BasicRangeAreaChart;
