// angular-material/src/app/charts/radialbar-charts/semi-circular-gauge-radialbar-chart/semi-circular-gauge-radialbar-chart.component.ts
import { Component, ViewChild } from '@angular/core';
import { MatCardModule } from '@angular/material/card';
import { RouterLink } from '@angular/router';

import {
    ApexNonAxisChartSeries,
    ApexPlotOptions,
    ApexChart,
    ApexFill,
    ChartComponent,
    NgApexchartsModule
} from "ng-apexcharts";

export type ChartOptions = {
    series: ApexNonAxisChartSeries;
    chart: ApexChart;
    colors: any;
    labels: string[];
    plotOptions: ApexPlotOptions;
    fill: ApexFill;
};

@Component({
    selector: 'app-semi-circular-gauge-radialbar-chart',
    standalone: true,
    imports: [RouterLink, MatCardModule, NgApexchartsModule],
    templateUrl: './semi-circular-gauge-radialbar-chart.component.html',
    styleUrl: './semi-circular-gauge-radialbar-chart.component.scss'
})
export class SemiCircularGaugeRadialbarChartComponent {

    @ViewChild("chart") chart: ChartComponent;
    public chartOptions: Partial<ChartOptions>;

    constructor() {
        this.chartOptions = {
            series: [76],
            chart: {
                type: "radialBar",
                offsetY: -20
            },
            plotOptions: {
                radialBar: {
                    startAngle: -90,
                    endAngle: 90,
                    track: {
                        background: "#e7e7e7",
                        strokeWidth: "97%",
                        margin: 5, // margin is in pixels
                        dropShadow: {
                            enabled: true,
                            top: 2,
                            left: 0,
                            opacity: 0.31,
                            blur: 2
                        }
                    },
                    dataLabels: {
                        name: {
                            show: false
                        },
                        value: {
                            offsetY: -2,
                            fontSize: "22px"
                        }
                    }
                }
            },
            fill: {
                type: "gradient",
                gradient: {
                    shade: "light",
                    shadeIntensity: 0.4,
                    inverseColors: false,
                    opacityFrom: 1,
                    opacityTo: 1,
                    // stops: [0, 50, 53, 91]
                }
            },
            labels: ["Average Results"],
            colors: ["#605DFF"]
        };
    }

}
<mat-card class="mb-25 border-radius d-block bg-white border-0 shadow-none">
    <mat-card-header>
        <mat-card-title>
            <h5 class="mb-0">
                Semi Circular Gauge RadialBar Chart
            </h5>
        </mat-card-title>
    </mat-card-header>
    <mat-card-content>
        <apx-chart
            [series]="chartOptions.series!"
            [chart]="chartOptions.chart!"
            [plotOptions]="chartOptions.plotOptions!"
            [labels]="chartOptions.labels!"
            [fill]="chartOptions.fill!"
        ></apx-chart>
    </mat-card-content>
</mat-card>

// nextjs-material-ui/src/components/Charts/RadialBar/SemiCircularGaugeRadialBarChart.tsx
"use client";

import React, { useEffect, useState } from "react";
import { ApexOptions } from "apexcharts";
import dynamic from "next/dynamic";
import {
  Card,
  Typography,
} from "@mui/material";

// Dynamically import react-apexcharts with Next.js dynamic import
const Chart = dynamic(() => import("react-apexcharts"), { ssr: false });

const SemiCircularGaugeRadialBarChart: React.FC = () => {

  // Chart
  const [isChartLoaded, setChartLoaded] = useState(false);

  useEffect(() => {
    setChartLoaded(true);
  }, []);

  const series = [ 76 ];

  const options: ApexOptions = {
    chart: {
      offsetY: -20
    },
    plotOptions: {
      radialBar: {
          startAngle: -90,
          endAngle: 90,
          track: {
              background: "#e7e7e7",
              strokeWidth: "97%",
              margin: 5, // margin is in pixels
              dropShadow: {
                  enabled: true,
                  top: 2,
                  left: 0,
                  opacity: 0.31,
                  blur: 2
              }
          },
          dataLabels: {
              name: {
                  show: false
              },
              value: {
                  offsetY: -2,
                  fontSize: "22px"
              }
          }
      }
  },
  fill: {
      type: "gradient",
      gradient: {
          shade: "light",
          shadeIntensity: 0.4,
          inverseColors: false,
          opacityFrom: 1,
          opacityTo: 1,
          // stops: [0, 50, 53, 91]
      }
  },
  labels: ["Average Results"],
  colors: ["#605DFF"]
  };

  return (
    <>
      <Card
        sx={{
          boxShadow: "none",
          borderRadius: "7px",
          mb: "25px",
          padding: { xs: "18px", sm: "20px", lg: "25px" },
        }}
        className="rmui-card"
      >
        <Typography
          variant="h3"
          sx={{
            fontSize: { xs: "16px", md: "18px" },
            fontWeight: 700,
            mb: "25px",
          }}
          className="text-black"
        >
          Semi Circular Gauge RadialBar Chart
        </Typography>

  
        {isChartLoaded && (
          <Chart
            options={options}
            series={series}
            type="radialBar"
            height={420}
            width={"100%"}
          />
        )}
      </Card>
    </>
  );
};

export default SemiCircularGaugeRadialBarChart;
