// nextjs-material-ui/src/components/Charts/PieCharts/BasicPieChart.tsx
"use client";

import React, { useEffect, useState } from "react";
import { ApexOptions } from "apexcharts";
import dynamic from "next/dynamic";
import {
  Card,
  Box,
  Typography,
} from "@mui/material";

// Dynamically import react-apexcharts with Next.js dynamic import
const Chart = dynamic(() => import("react-apexcharts"), { ssr: false });

const BasicPieChart: React.FC = () => {

  // Chart
  const [isChartLoaded, setChartLoaded] = useState(false);

  useEffect(() => {
    setChartLoaded(true);
  }, []);

  const series = [ 60, 30, 10 ];

  const options: ApexOptions = {
    labels: [
      "Completed", "New Order", "Pending"
    ],
    colors: [
        "#37D80A", "#605DFF", "#AD63F6"
    ],
    legend: {
        show: true,
        fontSize: '12px',
        position: 'bottom',
        horizontalAlign: 'center',
        itemMargin: {
            horizontal: 8,
            vertical: 0
        },
        labels: {
            colors: '#64748B'
        },
        markers: {
            offsetX: -2,
            offsetY: -.5
        }
    },
    dataLabels: {
        enabled: false
    }
  };

  return (
    <>
      <Card
        sx={{
          boxShadow: "none",
          borderRadius: "7px",
          mb: "25px",
          padding: { xs: "18px", sm: "20px", lg: "25px" },
        }}
        className="rmui-card"
      >
        <Typography
          variant="h3"
          sx={{
            fontSize: { xs: "16px", md: "18px" },
            fontWeight: 700,
            mb: "25px",
          }}
          className="text-black"
        >
          Basic Pie Chart
        </Typography>

        <Box
          sx={{
            marginTop: "-10px", 
          }}
        >
          {isChartLoaded && (
            <Chart
              options={options}
              series={series}
              type="pie"
              height={360}
              width={"100%"}
            />
          )}
        </Box>
      </Card>
    </>
  );
};

export default BasicPieChart;

// angular-material/src/app/charts/pie-charts/basic-pie-chart/basic-pie-chart.component.ts
import { Component, ViewChild } from '@angular/core';
import { MatCardModule } from '@angular/material/card';
import { RouterLink } from '@angular/router';
import {
    ApexChart,
    ApexLegend,
    ApexDataLabels,
    ChartComponent,
    NgApexchartsModule,
    ApexNonAxisChartSeries,
} from "ng-apexcharts";

export type ChartOptions = {
    series: ApexNonAxisChartSeries;
    dataLabels: ApexDataLabels;
    legend: ApexLegend;
    chart: ApexChart;
    colors: string[];
    labels: any;
};

@Component({
    selector: 'app-basic-pie-chart',
    standalone: true,
    imports: [RouterLink, MatCardModule, NgApexchartsModule],
    templateUrl: './basic-pie-chart.component.html',
    styleUrl: './basic-pie-chart.component.scss'
})
export class BasicPieChartComponent {

    @ViewChild("chart") chart: ChartComponent;
    public chartOptions: Partial<ChartOptions>;

    constructor() {
        this.chartOptions = {
            series: [60, 30, 10],
            chart: {
                height: 360,
                type: "pie"
            },
            labels: [
                "Completed", "New Order", "Pending"
            ],
            colors: [
                "#37D80A", "#605DFF", "#AD63F6"
            ],
            legend: {
                show: true,
                fontSize: '12px',
                position: 'bottom',
                horizontalAlign: 'center',
                itemMargin: {
                    horizontal: 8,
                    vertical: 0
                },
                labels: {
                    colors: '#64748B'
                },
                markers: {
                    width: 9,
                    height: 9,
                    offsetX: -2,
                    offsetY: -.5
                }
            },
            dataLabels: {
                enabled: false
            }
        };
    }

}
<mat-card class="mb-25 border-radius d-block bg-white border-0 shadow-none">
    <mat-card-header>
        <mat-card-title>
            <h5 class="mb-0">
                Basic Pie Chart
            </h5>
        </mat-card-title>
    </mat-card-header>
    <mat-card-content>
        <div class="chart">
            <apx-chart
                [chart]="chartOptions.chart!"
                [series]="chartOptions.series!"
                [legend]="chartOptions.legend!"
                [colors]="chartOptions.colors!"
                [labels]="chartOptions.labels!"
                [dataLabels]="chartOptions.dataLabels!"
            ></apx-chart>
        </div>
    </mat-card-content>
</mat-card>
